language: ruby
rvm:
- 2.4.0
deploy:
  provider: heroku
  api_key:
    secure: NiiW04fGYtLovxDmlIRM6346JZt2BE3aWNiDNWuyVhX5LsVGstYz4607d8RlNW51ki1f44G7tBGQUj4ATN78LnhFJ4Fs0LDjfFy9pe0/UTISo5ETzHyVnJS7iAjGZkR8y5g1u6uiMH28GgIImcVn0n5ZdeyBOlpkZV3mZSZ9hcT5LtFnXtpCfCNAtys2qw29fnsqd1/xviy5wafK4jklgmpYuYdOcFIwQ9MXvFIt56vkMAwyrqQQRLu/d4o+q1XT5gmeZ1s3H6F+rmbcXZIrZwvS25cH5blYM/HLbVI+8Tplq6KyWqv5lrMFS4H+xjC1KtvTr1boP5H/r7zvWOJtgKDUTcqUvc4EOHZtmXcZvETlUGFQyt/DFTh9Y30vDdEQq6AXhox4BgPIQsh06qqDIRcV3XIgSxPySsOaEWFGaXSX6WMA0dkzHmjsu8Mp/D0tlzmux8n0lpMfci6KcqhA9qPoazlhIHMkhyC0tCyeUlWcLRIss1C69pLYYjZ7k18NHVNoHbt0pC8PU/3cm5nyZ/E/bfBxfOuV+sHk/OK3GLn19W5RwzhacnujZGXbIcsuq6A+0COkhzdPsUj9PtzQE68yRGJqCq3s+XG8Xwf/w0wF7dN8DYJzIdmbLBi84eX8H/hwnE1zmHuDPmqw0CwwO/ILg6lXfzgpfy3BiE0aK8k=
  run: "rake db:migrate"