#Ruby environment
language: ruby
rvm:
  - 2.4.0

#PostgreSQL environment
services:
  - postgresql
before_script:
  - psql -c 'create database etraction_test;' -U postgres

#CodeClimate test coverage
addons:
  code_climate:
    repo_token:
      secure: "wlBUxw1aMlrb+RiFapkzklVScg8ZsthBny8rkNseOhr5j2ke66hxL+cPe1NC6dP/tDSPWaGvTlp1IbvfZV5ZOH9pv/F65SCePURXWv9UXyWVte6KMJBzb1nOUgmP/dUkqe8lkgQ9zaqb1OO9s1vueCjJeRQ2e63x1ERO1rtmijhDP+BPfPEu+jhF/6xd4NmfL7Zt7ocJnVqyR9tU6IZgcxIIXBoPxr0XX4fQI4EJVZrBvEBLg0IErOJg5Ve0Wa1l1/duVXK3lQ4pcI+t/fWzrP6xxQsQh15Xpr5dENgA9FDtrpnNXqpOKijkjxtgZ/wIE1vEq+7Lbl3a7BtDEMaQGM+F15ahI4KUJowzT02SN2lvSXER03VqJmxZb3nrIub5j5O+rlyrql3avWIMEKXIWsNdFWo6JhPPHXykEhFL4iDwLhUhr48eki6H4nX6AMGilLhVmzY3no/AfKUR7NS0e4ufAyx8N50Kw77Ltuan2uPEwNv7Y/SihVnRaDezV1PuTJwi8rxZqpTaZPejpzouST3Hu91l6vSO6um5X8HIIGv6DiDhZ052Nx+dobdJGYpaJ4BOKABWsYbK7RJMi00ItJaalo078ZNIzBYGLD4lz7nhTiJmRfVt1KF3iFsEyWF7c5RDwMlRxcdxcv9AcL8BQBwK+RQRuJi6mmL/+fLFRiA="
after_success:
  - bundle exec codeclimate-test-reporter

#Heroku deploy
deploy:
  provider: heroku
  api_key:
    secure: pIwAfA4daBUWU/vI2LGnvsVn0BEsq8U060S+z3QaT7PG6KFGgzFA4cOPRagGkMJwqjaDVibjnLnb08J8zr0uRaGjpgm1NSXHdMandTyOIChcl3E0GQGf8eyrhGzU21o9x4xrtM/QuQ7BaZf/It40JNRKTsBq/SmShBaEO1gkRdkLp++nlaVocdxfw8R/o/90e4VQjmjeD1WdxiLsut6jnMS4F23Ze6Iq0UGofr7GxQAq7ILLgKzQkjT6yH3lUtkP/EIFkIY9OA0UEOKkpM8hgcp5GtU9B2URZ6MsgUcnY4KxGISL17ivLO/XS8w+KNfui8LUqcQVXMXjz1v91BZ/c3CqmpS2mZUarGTNqQ3d5zX5XVR/OwqrIeSWRRaxLgP1/hlrVFWo1hA8Yr6ua/JVeR3FNmZ4tEHCrhTndA1imEUj4VorAEUUzaF7Hmd4wMeUd70+vresrDIGTCNUcJpySO2b3X8gQpHasS567Dq61Z1DBvm3q9niscu0+R+wesMZCKx7R68cmv6+4Q0NvGOUf9bruWsW+a5nB3g0QqyBt/JZdn3e8F4TUkk+J1zASK3BHbRJqc72UIZp1o3y0im/ahXzO6yfKRhcaG+gV7eihR0AeqHf3LQW67zXWJJ4tkeua+yk/dEkRuznaYMm9Pz1jxbP2yxjen1n7oZ5Wx6P2sI=
  app: etraction
  on:
    repo: gracz21/eTraction
  run: "rake db:migrate"
