default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  username: gracz21
  database: etraction_development

test:
  <<: *default
  database: etraction_test

production:
  <<: *default
  database: etraction_production
