default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: gracz21

development:
  <<: *default
  database: etraction_development

test:
  <<: *default
  database: etraction_test

production:
  <<: *default
  database: etraction_production
